### ISSUE TITLE
Truffle Compile SyntaxError

### ISSUE THREAD

**Issue by whitbirs** [ConsenSys-archive/truffle#6200]
:1
ELF
^

SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at requireFromString (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/require-from-string/index.js:28:1)
    at VersionRange.compilerFromString (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/compilerSupplier/loadingStrategies/VersionRange.js:95:1)
    at VersionRange.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/compilerSupplier/loadingStrategies/VersionRange.js:111:1)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/compilerSupplier/loadingStrategies/VersionRange.js:5:43)
Truffle v5.11.5 (core: 5.11.5)
Node v18.18.0

I just follow the project from https://trufflesuite.com/guides/nft-marketplace/, when I come to the step of compiling the contracts in the "ethereum" file, it doesn't work, and I got the error like that. 

How can I modify it？

**Comment by MadelineMurray** [comment]
hi @whitbirs - Truffle is being sunset.  For more information and migration options, click [here](https://consensys.io/blog/consensys-announces-the-sunset-of-truffle-and-ganache-and-new-hardhat?utm_source=github&utm_medium=referral&utm_campaign=2023_Sep_truffle-sunset-2023_announcement_).
